name: Restart MessageApp Service

on:
  push:
    branches:
      - main  # Adjust the branch name if needed
  pull_request:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  restart-service:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'oracle'
        cache: 'maven'

    - name: Build with Maven
      run: mvn clean install

    - name: Restart Application Service
      run: |
        sudo systemctl restart messageapp.service
