name: Restart MessageApp Service

on:
  push:
    branches:
      - main  # Adjust the branch name if needed
  pull_request:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  restart-service:
    runs-on: ubuntu-20.04

    steps:
#    - name: Checkout code
#      uses: actions/checkout@v3
#
#    - name: Set up JDK 17
#      uses: actions/setup-java@v2
#      with:
#        java-version: '17'
#        distribution: 'adopt'
#        cache: 'maven'
#
#    - name: Build with Maven
#      run: mvn clean install -DskipTests

    - name: Restart Application Service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GOOGLE_HOST }}
        username: ${{ secrets.GOOGLE_USERNAME }}
        key: ${{ secrets.GOOGLE_SSH_KEY }}
        script: |
          sudo systemctl restart messageapp.service
